[tool.poetry]
name = "hackathon-aixlaw"
version = "0.1.0"
description = ""
authors = ["Jordan Parker <jordanhparker6@gmail.com>"]
readme = "README.md"
packages = [{include = "hackathon_aixlaw"}]

[tool.poetry.dependencies]
python = "^3.10"
langchain = "^0.0.300"
structlog = "^23.1.0"
fastapi = "^0.103.1"
tenacity = "^8.2.3"
python-dotenv = "^1.0.0"
pdf2image = "^1.16.3"
unstructured = "^0.10.16"
nougat-ocr = "^0.1.13"
fitz = "^0.0.1.dev2"
pymupdf = "^1.23.3"
openai = "^0.28.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
ipykernel = "^6.25.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
